language: node_js
node_js:
  - "0.11"
  - "0.10"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
 
script: 
- "npm run-script travis"
- "node ./bin/bt.js --url http://www.sitespeed.io --browser firefox --runs 2"

