language: node_js
node_js:
  - "0.11"
  - "0.10"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
 
script: 
- "npm run-script travis"
- "node ./bin/browsertime.js -u http://www.sitespeed.io -b firefox -n 2 --useProxy false"
- "node ./bin/browsertime.js -u http://www.sitespeed.io -b firefox -n 2 --proxySleepBeforeStart 6000"

