name: Question
description: Ask a question about Browsertime
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Ask a question about Browsertime
  - type: textarea
    id: your-question
    attributes:
      label: Your question
      description: Please double check that this question hasn't already answered in [old GitHub issues](https://github.com/sitespeedio/sitespeed.io/issues?q=is%3Aissue+is%3Aclosed). You can also ask questions in the [sitespeed.io Slack channel](https://sitespeedio.herokuapp.com/).
    validations:
      required: true